SELECT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos WHERE SABOR = 'LARANJA';

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM tabela_de_produtos;


SELECT * FROM tabela_de_clientes;

SELECT DISTINCT BAIRRO FROM tabela_de_clientes WHERE CIDADE = 'RIO DE JANEIRO';